on: push
name: 🚀 Deploy to PM2 server on push
jobs:
  preview-server-deploy:
    name: 🎉 Deploy to PM2 Server!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./deploy.pem
          sudo chmod 600 ./deploy.pem
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Install PM2
        run: npm i -g pm2

      - name: Deploy
        run: pm2 deploy ecosystem.config.js development
